// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZ6i7h7Eaf0P1nC9GdukmYOGFvw-WYvg',
    appId: '1:1098734207320:web:3ef34baf7a84d96504652d',
    messagingSenderId: '1098734207320',
    projectId: 'socialapp-779fd',
    authDomain: 'socialapp-779fd.firebaseapp.com',
    storageBucket: 'socialapp-779fd.firebasestorage.app',
    measurementId: 'G-8L3M089QM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7g3n-l_JgT9koFUIezIDecwvHVkEEREY',
    appId: '1:1098734207320:android:377ebca3ea0d0bd904652d',
    messagingSenderId: '1098734207320',
    projectId: 'socialapp-779fd',
    storageBucket: 'socialapp-779fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4H4eiW4dmti2Zl56VC33zUP2XG8LKrk',
    appId: '1:1098734207320:ios:55bd84510d87284b04652d',
    messagingSenderId: '1098734207320',
    projectId: 'socialapp-779fd',
    storageBucket: 'socialapp-779fd.firebasestorage.app',
    iosBundleId: 'com.example.practicalibreTadeXool',
  );
}
