// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQMa8gBp_paPtubp_yRTRKP3yCkqf6xw',
    appId: '1:599718907743:web:313afc8e66b2557f6eb0ea',
    messagingSenderId: '599718907743',
    projectId: 'socialappkevinsalazar',
    authDomain: 'socialappkevinsalazar.firebaseapp.com',
    storageBucket: 'socialappkevinsalazar.firebasestorage.app',
    measurementId: 'G-0MVRB3CL62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1cSd_p4WnplE0Blo2skAWDSzUZ1TvwA',
    appId: '1:599718907743:android:f47c25897af1883d6eb0ea',
    messagingSenderId: '599718907743',
    projectId: 'socialappkevinsalazar',
    storageBucket: 'socialappkevinsalazar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEzKjwi_KvLtD5ZWukYCdKk0IgkMuxxA',
    appId: '1:599718907743:ios:01447f7daf7f6e526eb0ea',
    messagingSenderId: '599718907743',
    projectId: 'socialappkevinsalazar',
    storageBucket: 'socialappkevinsalazar.firebasestorage.app',
    iosBundleId: 'com.example.socialAppKevinSalazar',
  );
}
